name: Crawl Data

on:
  schedule:
    - cron: '0 4 * * *'  # Run daily at 12:00 PM UTC+8 (4:00 AM UTC)
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: crawl
  cancel-in-progress: false

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Node.js and cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --loglevel=verbose

      - name: Crawl data
        run: npm run start

      - name: Checkout result branch
        uses: actions/checkout@v4
        with:
          ref: result
          path: result-branch

      - name: Sync crawled data
        run: |
          rsync -av --delete result/ result-branch/

      - name: Commit and push results
        working-directory: result-branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "$(TZ=Asia/Shanghai date +"%Y-%m-%d %H:%M:%S")"
          git push origin result
