name: Crawl Data

on:
  schedule:
    - cron: '0 4 * * *'  # Run daily at 12:00 PM UTC+8 (4:00 AM UTC)
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: crawl
  cancel-in-progress: false

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            chromium \
            libgbm-dev \
            libxshmfence-dev \
            libglu1-mesa-dev \
            libx11-dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Configure npm
        run: |
          npm config set registry https://registry.npmmirror.com
          echo "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1" >> $GITHUB_ENV
          echo "PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium" >> $GITHUB_ENV

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Base Dependencies
        run: npm ci --omit=optional --ignore-scripts --no-audit --no-fund

      - name: Install Puppeteer Core
        run: npm install puppeteer-core@21.7.0

      - name: Install ESBuild
        run: npm rebuild esbuild --platform=linux --arch=x64

      - name: Crawl data
        run: npm run start

      - name: Checkout result branch
        uses: actions/checkout@v4
        with:
          ref: result
          path: result-branch
          sparse-checkout: result  # 只检出 result 目录

      - name: Sync crawled data
        run: |
          mkdir -p result-branch/result
          rsync -av --delete result/ result-branch/result/

      - name: Commit and push results
        working-directory: result-branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add result/
          git commit -m "$(TZ=Asia/Shanghai date +"%Y-%m-%d %H:%M:%S")"
          git push origin result