name: Crawl Data

on:
  schedule:
    - cron: '0 4 * * *'  # Run daily at 12:00 PM UTC+8 (4:00 AM UTC)
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: crawl
  cancel-in-progress: false

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Crawl data
        run: npm run start
      - name: Push to result branch
        run: |
          git checkout -b result
          git add result/* -f
          git commit -m "$(TZ=Asia/Shanghai date +"%Y-%m-%d %H:%M:%S")"
          git push origin result
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}